from argparse import ArgumentParser
from re import finditer
from pathlib import Path
from sys import stdin

if __name__ == '__main__':
    argparser = ArgumentParser(description="Extract all valid tags from the rpcprotocol webpage")
    argparser.add_argument("input", help="Path to input file (rpc gui protocol page in HTML")

    args = argparser.parse_args()
    if args.input == "-":
        input_file = stdin
    else:
        input_file = Path(args.input)

    tags = set()
    with open(input_file, "r") as file:
        for line in file:
            for res in finditer(r"&lt;/?([a-z1-9_]+)/?&gt;", line):
                tags.add(res[1])

    print("# generated by protocol_to_tag.py")
    print()
    print("class Tag:")
    for tag in sorted(tags):
        print("    {} = \"{}\"".format(tag.upper(), tag.lower()))